version: '3.8'

services:
  classlog-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: classlog
      POSTGRES_PASSWORD: classlog
      POSTGRES_DB: classlog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # flyway:
  #   image: flyway/flyway
  #   depends_on:
  #     - classlog-db
  #   command: -url=jdbc:postgresql://classlog-db:5432/classlog -user=classlog -password=classlog migrate
  #   volumes:
  #     - ./db_scripts:/flyway/sql

volumes:
  postgres-data:
