version: "3.8"

services:
  classlog-frontend:
    build:
      context: ./classlog-frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:4200" # Use variable for the frontend port
    depends_on:
      - classlog-backend
      - classlog-db
    env_file:
      - .env

  classlog-backend:
    build:
      context: ./classlog-backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=custom
      - SPRING_ALLOWED_ORIGIN=${SPRING_ALLOWED_ORIGIN}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      classlog-db:
        condition: service_healthy
    env_file:
      - .env

  classlog-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  postgres-data:
