-- Inserting data into the ROLE table
INSERT INTO role (role_name) VALUES
    ('Teacher'),
    ('Student'),
    ('Admin'),
    ('Unknown');

-- Inserting data into the CLASSLOG_USER table
INSERT INTO classlog_user (name, surname, email, password, role_id) VALUES
    ('John', 'Doe', 'john@e.com', '$2b$12$eIsm8R0N3dBJw5bEeKAzFOk3ehlRpWhvEJoAAxLD9lp86KHuyoWXK', 1),  -- Teacher
    ('Jane', 'Smith', 'jane@e.com', '$2b$12$eIsm8R0N3dBJw5bEeKAzFOk3ehlRpWhvEJoAAxLD9lp86KHuyoWXK', 2),  -- Student
    ('Bob', 'Johnson', 'bob@e.com', '$2b$12$eIsm8R0N3dBJw5bEeKAzFOk3ehlRpWhvEJoAAxLD9lp86KHuyoWXK', 2),  -- Student
    ('Alice', 'Brown', 'alice@e.com', '$2b$12$eIsm8R0N3dBJw5bEeKAzFOk3ehlRpWhvEJoAAxLD9lp86KHuyoWXK', 1),  -- Teacher
    ('Alex', 'Alex', 'alex@e.com', '$2b$12$eIsm8R0N3dBJw5bEeKAzFOk3ehlRpWhvEJoAAxLD9lp86KHuyoWXK', null);  -- NULL

-- Inserting data into the CLASS table (code will be generated by trigger)
INSERT INTO class (name, description) VALUES
    ('English - Beginners', 'Welcome to basic English class'),
    ('English - Advanced', 'Class rules...'),
    ('German - Intermediate', 'Guten Tag!');

-- Inserting data into the USER_CLASS table (linking users to classes)
INSERT INTO user_class (class_id, user_id) VALUES
    (1, 1),
    (1, 2),
    (2, 1),
    (2, 3),
    (3, 4),
    (3, 2);

-- Inserting data into the QUESTION_TYPE table
INSERT INTO question_type (type_name) VALUES
    ('Multiple Choice'),
    ('Open Question');

-- Inserting data into the LESSON table
INSERT INTO lesson (created_by, class_id, lesson_date, subject, content) VALUES
    (1, 1, '2024-09-10 10:00:00', 'Introduction to Past Simple', 'HOMEWORK:...'),
    (4, 3, '2024-09-11 12:00:00', 'Past tenses', 'HOMEWORK:...'),
    (1, 2, '2024-09-12 14:00:00', 'Animals', 'HOMEWORK:...');

-- Inserting data into the TASK table
INSERT INTO task (created_by, lesson_id, task_name, due_date, description) VALUES
    (1, 1, 'TestExample1', '2024-09-15 23:59:59', 'Basic information about the task, some tips'),
    (4, 2, 'TestExample2', '2024-09-20 23:59:59', 'Basic information about the task, some tips'),
    (1, 3, 'History Essay', '2024-09-25 23:59:59', 'Basic information about the task, some tips');

-- Inserting data into the PRESENCE table
INSERT INTO presence (student_id, lesson_id) VALUES
    (2, 1),  -- Jane Smith attended the Algebra lesson
    (3, 3),  -- Bob Johnson attended the History lesson
    (2, 2);  -- Jane Smith attended the Mechanics lesson

-- Inserting data into the FILE table
INSERT INTO file (class_id, user_id, filename) VALUES
    (1, 1, 'Algebra_Notes.pdf'),  -- John Doe uploaded notes for Math 101
    (3, 4, 'Mechanics_Slides.pptx');  -- Alice Brown uploaded slides for Physics 101

-- Inserting data into the POST table
INSERT INTO post (class_id, user_id, title, content) VALUES
    (1, 1, 'Welcome to Math 101!', 'Welcome to Math 101. Please check the syllabus and lecture notes.'),
    (2, 1, 'History 101 - First Lecture Notes', 'The first lecture notes for History 101 have been uploaded.');

-- Inserting data into the COMMENT table
INSERT INTO comment (post_id, user_id, content) VALUES
    (1, 2, 'Thank you! I’m excited to start Math 101.'),
    (2, 3, 'Looking forward to the lecture notes on ancient Rome.');

INSERT INTO grade (class_id, student_id, teacher_id, grade, wage, description) VALUES
    (2,3,2,95,3,'TEST GRADE');

-- Inserting data into the QUESTION table
-- INSERT INTO question (task_id, question_type_id, filename, points, content) VALUES
--     (1, 1, NULL, 10, 'What is the value of x if 2x + 3 = 7?'),
--     (2, 2, NULL, 5, 'Newton’s second law states that Force equals mass times acceleration (True/False)?'),
--     (3, 4, NULL, 20, 'Discuss the contributions of ancient Greece to modern civilization.');
--
-- -- Inserting data into the ANSWER table
-- INSERT INTO answer (question_id, is_correct, content) VALUES
--     (1, TRUE, 'x = 2'),
--     (2, TRUE, 'True'),
--     (3, NULL, 'Answers may vary.');  -- Essay question, so correctness depends on the teacher
--
-- -- Inserting data into the SUBMITTED_ANSWER table
-- INSERT INTO submitted_answer (answer_id, user_id, content) VALUES
--     (1, 2, 'x = 2'),  -- Jane Smith’s submission for Algebra Homework
--     (2, 3, 'True'),  -- Bob Johnson’s submission for Mechanics Assignment
--     (3, 2, 'Ancient Greece contributed to modern democracy, philosophy, and the arts.');  -- Jane Smith’s submission for History Essay


