version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: classlog-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_initializer/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "${DB_PORT}", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  db_data:

