version: "3.8"

services:
  backend:
    build:
      context: ../classlog-backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: custom
      SPRING_ALLOWED_ORIGIN: http://${FRONTEND_ADDRESS}:${FRONTEND_PORT}
      DB_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}                                
      DB_USERNAME: ${DB_USERNAME}                      
      DB_PASSWORD: ${DB_PASSWORD}  
      ADMIN_EMAIL: ${ADMIN_EMAIL}                                        
    ports:
      - "${BACKEND_PORT}:8080" 
    env_file:
      - .env 
