version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: classlog-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - classlog-network
    env_file:
      - .env


  initializer:
    build:
      context: ./db_initializer
      dockerfile: Dockerfile
    container_name: classlog-initializer
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - db
    networks:
      - classlog-network
    env_file:
      - .env

volumes:
  db_data:

networks:
  classlog-network:
    driver: bridge
