version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: classlog-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - classlog-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "${DB_PORT}", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  initializer:
    build:
      context: ./db_initializer
      dockerfile: Dockerfile
    container_name: classlog-initializer
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - db
    networks:
      - classlog-network
    env_file:
      - .env

  backend:
    build:
      context: ../classlog-backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: custom
      SPRING_ALLOWED_ORIGIN: http://${FRONTEND_ADDRESS}:${FRONTEND_PORT}
      DB_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}                              
      DB_USERNAME: ${DB_USERNAME}                      
      DB_PASSWORD: ${DB_PASSWORD}                     
    ports:
      - "${BACKEND_PORT}:8080" 
    depends_on:
      - db
    networks:
      - classlog-network
    env_file:
      - .env

  frontend:
    build:
      context: ../classlog-frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://${BACKEND_ADDRESS}:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend
      - db
    networks:
      - classlog-network
    env_file:
      - .env


volumes:
  db_data:

networks:
  classlog-network:
    driver: bridge
