version: "3.8"

services:
  frontend:
    build:
      context: ../classlog-frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://${BACKEND_ADDRESS}:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:4200"
    env_file:
      - .env

