spring:
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false # Serialize dates in ISO 8601 format
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS # Date format with milliseconds precision
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB       # Maximum size of a single file
      max-request-size: 30MB    # Maximum size of a request (including all files and data)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/classlog
    username: classlog
    password: classlog
  admin:
    email: ${ADMIN_EMAIL}
custom:
  cors:
    allowed-origin: http://localhost:4200

---
spring:
  config:
    activate:
      on-profile: custom
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  admin:
    email: ${ADMIN_EMAIL}
custom:
  cors:
    allowed-origin: ${SPRING_ALLOWED_ORIGIN:*}
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  admin:
    email: "test"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
custom:
  cors:
    allowed-origin: http://localhost:4200
